# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/segment.ui'
#
# Created: Fri May 30 16:44:51 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PropertiesWidget(object):
    def setupUi(self, PropertiesWidget):
        PropertiesWidget.setObjectName("PropertiesWidget")
        PropertiesWidget.resize(347, 409)
        self.verticalLayout = QtGui.QVBoxLayout(PropertiesWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(PropertiesWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._doubleSpinBoxPointSize = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._doubleSpinBoxPointSize.sizePolicy().hasHeightForWidth())
        self._doubleSpinBoxPointSize.setSizePolicy(sizePolicy)
        self._doubleSpinBoxPointSize.setMinimum(0.01)
        self._doubleSpinBoxPointSize.setMaximum(999999.99)
        self._doubleSpinBoxPointSize.setProperty("value", 2.0)
        self._doubleSpinBoxPointSize.setObjectName("_doubleSpinBoxPointSize")
        self.verticalLayout_2.addWidget(self._doubleSpinBoxPointSize)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_8 = QtGui.QGroupBox(PropertiesWidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self._checkBoxStreamingCreate = QtGui.QCheckBox(self.groupBox_8)
        self._checkBoxStreamingCreate.setObjectName("_checkBoxStreamingCreate")
        self.verticalLayout_11.addWidget(self._checkBoxStreamingCreate)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_10 = QtGui.QGroupBox(PropertiesWidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtGui.QLabel(self.groupBox_10)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self._doubleSpinBoxStepSize = QtGui.QDoubleSpinBox(self.groupBox_10)
        self._doubleSpinBoxStepSize.setProperty("value", 1.0)
        self._doubleSpinBoxStepSize.setObjectName("_doubleSpinBoxStepSize")
        self.horizontalLayout_2.addWidget(self._doubleSpinBoxStepSize)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self._pushButtonPushDown = QtGui.QPushButton(self.groupBox_10)
        self._pushButtonPushDown.setMinimumSize(QtCore.QSize(99, 0))
        self._pushButtonPushDown.setObjectName("_pushButtonPushDown")
        self.horizontalLayout_6.addWidget(self._pushButtonPushDown)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self._pushButtonPullUp = QtGui.QPushButton(self.groupBox_10)
        self._pushButtonPullUp.setMinimumSize(QtCore.QSize(99, 0))
        self._pushButtonPullUp.setObjectName("_pushButtonPullUp")
        self.horizontalLayout_6.addWidget(self._pushButtonPullUp)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.groupBox_11 = QtGui.QGroupBox(PropertiesWidget)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self._pushButtonDelete = QtGui.QPushButton(self.groupBox_11)
        self._pushButtonDelete.setObjectName("_pushButtonDelete")
        self.horizontalLayout_5.addWidget(self._pushButtonDelete)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_11)

        self.retranslateUi(PropertiesWidget)
        QtCore.QMetaObject.connectSlotsByName(PropertiesWidget)

    def retranslateUi(self, PropertiesWidget):
        PropertiesWidget.setWindowTitle(QtGui.QApplication.translate("PropertiesWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PropertiesWidget", "Point Size", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("PropertiesWidget", "Create Mode", None, QtGui.QApplication.UnicodeUTF8))
        self._checkBoxStreamingCreate.setToolTip(QtGui.QApplication.translate("PropertiesWidget", "Add nodes in streaming mode ", None, QtGui.QApplication.UnicodeUTF8))
        self._checkBoxStreamingCreate.setText(QtGui.QApplication.translate("PropertiesWidget", "Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("PropertiesWidget", "Push/Pull", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PropertiesWidget", "Step size:", None, QtGui.QApplication.UnicodeUTF8))
        self._doubleSpinBoxStepSize.setToolTip(QtGui.QApplication.translate("PropertiesWidget", "Set the depth for pushing/pulling segmentation points down/up a layer", None, QtGui.QApplication.UnicodeUTF8))
        self._pushButtonPushDown.setText(QtGui.QApplication.translate("PropertiesWidget", "Push Down", None, QtGui.QApplication.UnicodeUTF8))
        self._pushButtonPullUp.setText(QtGui.QApplication.translate("PropertiesWidget", "Pull Up", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("PropertiesWidget", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self._pushButtonDelete.setToolTip(QtGui.QApplication.translate("PropertiesWidget", "Remove selected segmentation points", None, QtGui.QApplication.UnicodeUTF8))
        self._pushButtonDelete.setText(QtGui.QApplication.translate("PropertiesWidget", "Delete", None, QtGui.QApplication.UnicodeUTF8))

from . import images_rc
